travis:
  secure:
    BINSTAR_TOKEN: ZerVVkv2aJ/qCx4Q6OIN+JvZC5KXy0njkfyg7HgYKN9C4tSALXJeMxV3hKfyDFdUdSGwwNSyu4nyN1GG4HZeJcnf7Hw0cDKmvuncIgTd1DWbzdrmQQjgWZXYY8R5owHymDB81MxNhR9CcytmuCrR2kSuuAneBZ9Tyi5r/We6V3afzbHSC2cRLfqNVFrHkAtRrkwW3h+9WiLRkFPMFIPfAV9bkeHM1XPh8BVZbxyuB/3d/tn4xUp+nF2GLpKIdNhAMAjUKtrW/b1WbEuA1Nzi+Sg7CXc7kE0jcRtjRxu8bjojFvD1RruMC7P8aXHx/wWDQmjiLDGyEMR3qsJ9uDLG6jLY2xNuLzsd25Ake9ASUOkPKQN9ZSiOw2H3YJbVn4NDXgcRB/KN4eV30RNuaEwVX5tQJoXyYcBR0Ee7xo4Qs3/HmGZAqV6kPKwfxgbXuD3M7ppELAEpxsaKv8KRzAtL+S6+TKqwvA8qJMY3veDkGX7yfpRsYNrZFnZp4Wr06WQHiG0OecP5syHbK/9C6kLVt78Hmrkw1hZ/NbN0qkn0m95xJS/7ohnkmkTkyXoY86/koaguXNAOFAVs2pZxBEJJUp52UfFQJUJIYt0ehMJsp00PANOVio9w+ODhdTLe7OosNmXmxoKqpUPm/vCFHInjEZKuTVj4fFJ9Tcs+f8XwnlU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
